"""
constants.py

Internal constants.

Do not edit this file.
User parameters are defined in config.py.
"""

from config import *

# ============================================================
# Mathematical constants
# ============================================================

GRAVITY_M_S2 = 9.80665

# ============================================================
# Derived quantities
# ============================================================

BALL_INERTIA_KG_M2 = (
    2.0 / 5.0
    * BALL_MASS_KG
    * BALL_RADIUS_M**2
)

# ============================================================
# Unit conversions
# ============================================================

MM_TO_M = 1e-3
M_TO_MM = 1e3

G_TO_KG = 1e-3
KG_TO_G = 1e3

UF_TO_F = 1e-6
